function create_gt_files(GLM_stats, RP)

    fprintf('Calculating Ground Truth Data...\n');

    % Set ground truth flag
    RP.cluster_stat_type = 'ground_truth';

    % Generate file names
    [existence_edge, file_path_edge] = create_and_check_rep_file(RP.save_directory, RP.data_set, RP.test_name, ...
                                                                 RP.test_type, 'Parametric_Bonferroni', 'nobus', RP.n_subs_subset, ...
                                                                 RP.testing, RP.ground_truth);
    [existence_network, file_path_network] = create_and_check_rep_file(RP.save_directory, RP.data_set, RP.test_name, ...
                                                                       RP.test_type, 'Constrained', 'nobus', RP.n_subs_subset, ...
                                                                       RP.testing, RP.ground_truth);
    [existence_whole_brain, file_path_whole_brain] = create_and_check_rep_file(RP.save_directory, RP.data_set, RP.test_name, ...
                                                                              RP.test_type, 'Omnibus', 'nobus', RP.n_subs_subset, ...
                                                                              RP.testing, RP.ground_truth);

    % Check if all GT files exist
    if existence_edge && existence_network && existence_whole_brain && RP.recalculate == 0
        fprintf('Ground Truth Data already exists. Skipping...\n');
        return;
    end


    % Prepare data for saving
    gt_data_edge = GLM_stats.edge_stats_all;
    gt_data_network = GLM_stats.cluster_stats_all;
    % gt_data_whole_brain = gt_data_network;  % Aggregate over all networks

    brain_data = add_brain_data_to_repetition_data('edge_stats_all', gt_data_edge, ...
                                                    'cluster_stats_all', gt_data_network, ...
                                                    'FWER', NaN);

    meta_data = add_meta_data_to_repetition_data('dataset', RP.data_set_base, ...
                                                 'map', RP.data_set_map, 'test', RP.test_type, ...
                                                 'test_components', strsplit(RP.test_name, '_'), ...
                                                 'omnibus', 'nobus', 'subject_number', RP.n_subs_subset, ...
                                                 'testing_code', RP.testing, 'test_type', 'Parametric_Bonferroni', ...
                                                 'rep_parameters', RP, 'date', datetime("today"), ...
                                                 'run_time', NaN);  % GT has no run-time

    save(file_path_edge, 'brain_data', 'meta_data');

    
    meta_data = add_meta_data_to_repetition_data('dataset', RP.data_set_base, ...
                                                 'map', RP.data_set_map, 'test', RP.test_type, ...
                                                 'test_components', strsplit(RP.test_name, '_'), ...
                                                 'omnibus', 'nobus', 'subject_number', RP.n_subs_subset, ...
                                                 'testing_code', RP.testing, 'test_type', 'Constrained', ...
                                                 'rep_parameters', RP, 'date', datetime("today"), ...
                                                 'run_time', NaN);  % GT has no run-time
    
    save(file_path_network, 'brain_data', 'meta_data')

    
    meta_data = add_meta_data_to_repetition_data('dataset', RP.data_set_base, ...
                                                 'map', RP.data_set_map, 'test', RP.test_type, ...
                                                 'test_components', strsplit(RP.test_name, '_'), ...
                                                 'omnibus', 'nobus', 'subject_number', RP.n_subs_subset, ...
                                                 'testing_code', RP.testing, 'test_type', 'Omnibus', ...
                                                 'rep_parameters', RP, 'date', datetime("today"), ...
                                                 'run_time', NaN);  % GT has no run-time
    

    save(file_path_whole_brain, 'brain_data', 'meta_data')

end