function [gt_directory, gt_output_name] = setup_gt_directory(Params)
    %%%
        % This function sets up the ground truth name to be compared with
        % the parameters
        % It assumes the gt follows the parameter directory generated by
        % the power calculator:
        % [~, output_name, ground_truth] 
        % If the gt_data_dir parameter is not filled, we assume the gt is
        % in the output directory
    %%%

    if ~isfield(Params, 'gt_data_dir')
        gt_directory = [Params.save_directory, Params.output, '/ground_truth/'];
        gt_output_name = Params.output;
        
    else
        gt_directory = Params.gt_data_dir;
        
        % Remove trailing slash
        gt_output_name = Params.gt_data_dir;
        if endsWith(gt_output_name, filesep)
            gt_output_name = gt_output_name(1:end-1);
        end

        % Go up one level to get the parent directory and extract 
        [gt_output_name, ~, ~] = fileparts(gt_output_name);  
        [~, gt_output_name, ~] = fileparts(gt_output_name); 
    end
   
end