%% Numerical comparison: traditional TFCE (C++) vs IC-TFCE (C++)
% Compares apply_tfce_cpp (IC-TFCE) against traditional_tfce_cpp over many
% random synthetic t-statistic matrices, each generated with a randomly
% drawn smoothing parameter (sigma). Reports the mean and standard
% deviation, across repetitions, of the absolute differences between the
% two outputs.
%
% Requires: apply_tfce_cpp and traditional_tfce_cpp compiled and on the
% path, and the Image Processing Toolbox (fspecial, imfilter).
% Both of those are generated by mex compilation form the PRISME toolbox

clear; 
clc;

%% Configuration
seed       = 42;            % RNG seed (reproducibility)
n_reps     = 50000;          % Number of random matrices
N          = 268;           % Number of ROIs
dh         = 0.1;           % TFCE step size
H          = 3.0;           % Height exponent 
E          = 0.4;           % Extent exponent
sigma_frac = [0.005, 0.10]; % Range of the Gaussian sigma
tol        = 1e-10;          % Tolerance used to count "large" differences

rng(seed);

%% Storage (one entry per repetition)
mean_abs_diff = zeros(n_reps, 1);
max_abs_diff  = zeros(n_reps, 1);
max_tfce      = zeros(n_reps, 1);   
sigmas        = zeros(n_reps, 1);

% Compare only the unique edges (upper triangle, no diagonal)
edge_mask = triu(true(N), 1);

%% Main loop
for rep = 1:n_reps

    % Random smoothing parameter for this repetition
    sigma = (sigma_frac(1) + rand() * (sigma_frac(2) - sigma_frac(1))) * N;
    sigmas(rep) = sigma;

    t_mat = l_generate_synthetic_tstat(N, sigma);

    % NOTE: The argument orders are different
    %   traditional_tfce_cpp(matrix, H, E, dh)
    %   apply_tfce_cpp(matrix, dh, H, E)
    
    % This is the traditional TFCE computation
    tfce_trad = traditional_tfce_cpp(t_mat, H, E, dh);

    % apply_tfce_cpp modifies its input array in place
    % so a copy is passed
    % This is the IC TFCE one
    tfce_ic = apply_tfce_cpp(t_mat + 0, dh, H, E);

    d = abs(tfce_trad(edge_mask) - tfce_ic(edge_mask));

    mean_abs_diff(rep) = mean(d);
    max_abs_diff(rep)  = max(d);
    max_tfce(rep)      = max(tfce_trad(edge_mask));
end

%% Summary
[worst_diff, worst_rep] = max(max_abs_diff);

fprintf('\n=== Traditional TFCE vs IC-TFCE (%d repetitions) ===\n', n_reps);
fprintf('N = %d ROIs, dh = %.3f, H = %.1f, E = %.1f, seed = %d\n', N, dh, H, E, seed);
fprintf('Sigma range: [%.2f, %.2f] (fraction of N: [%.3f, %.3f])\n', ...
    sigma_frac(1) * N, sigma_frac(2) * N, sigma_frac(1), sigma_frac(2));
fprintf('\n');
fprintf('Mean absolute difference (per matrix): mean = %.3e, std = %.3e\n', ...
    mean(mean_abs_diff), std(mean_abs_diff));
fprintf('Max absolute difference  (per matrix): mean = %.3e, std = %.3e\n', ...
    mean(max_abs_diff), std(max_abs_diff));
fprintf('Worst-case max absolute difference: %.3e (repetition %d, sigma = %.2f)\n', ...
    worst_diff, worst_rep, sigmas(worst_rep));
fprintf('Repetitions with max absolute difference > %.0e: %d of %d\n', ...
    tol, sum(max_abs_diff > tol), n_reps);
fprintf('Scale of TFCE values (max per matrix): mean = %.3e, std = %.3e\n', ...
    mean(max_tfce), std(max_tfce));

%% Local functions
% Generate random t-statistics and apply a Gaussian smoothing filter
function t_mat = l_generate_synthetic_tstat(N, sigma)

    raw = randn(N);
    
    ksize  = 2 * ceil(3 * sigma) + 1;
    kernel = fspecial('gaussian', ksize, sigma);
    
    smoothed = imfilter(raw, kernel, 0, 'same');
    smoothed = smoothed / std(smoothed(:)) * 3;
    
    t_mat = (smoothed + smoothed') / 2;
    t_mat(1:N+1:end) = 0;

end